import { exec } from "child_process";
import path from "path";
import fs from "fs";

export const runPerformanceTests = (baseUrl) => {
  return new Promise((resolve, reject) => {
    const scriptPath = path.resolve("tests/performance/load-test.js");
    const summaryPath = path.resolve("summary.json");

    const command = `k6 run --summary-export="${summaryPath}" "${scriptPath}"`;

    exec(
      command,
      {
        cwd: process.cwd(),
        env: { ...process.env, TARGET_URL: baseUrl },
        maxBuffer: 1024 * 1024 * 10, // prevent buffer overflow crash
      },
      (error, stdout, stderr) => {
        console.log("k6 STDOUT:\n", stdout);
        console.log("k6 STDERR:\n", stderr);

        if (error) {
          console.error("k6 execution error:", error.message);
          return reject(error.message);
        }

        try {
          if (!fs.existsSync(summaryPath)) {
            throw new Error("summary.json not generated by k6");
          }

          const summaryRaw = fs.readFileSync(summaryPath, "utf8");
          const summary = JSON.parse(summaryRaw);

          const metrics = {
            vus: summary.metrics.vus?.max || 0,
            avgResponseTime: Math.round(
              summary.metrics.http_req_duration?.avg || 0
            ),
            failureRate: summary.metrics.http_req_failed?.rate || 0,
            requests: summary.metrics.http_reqs?.count || 0,
          };

          resolve(metrics);
        } catch (parseError) {
          console.error("Error parsing k6 summary:", parseError);
          reject(parseError.message);
        }
      }
    );
  });
};
